// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgodaugjaycwugkescmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnb2RhdWdqYXljd3Vna2VzY21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzM2ODUsImV4cCI6MjA2OTgwOTY4NX0.0KwS_eMzupdNwJcv1TuwIMwwzFsuktLa969PBSrob4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});